### PR TITLE
git-annex.cabal: persistent ==2.2.4.1

### PR DESCRIPTION
**Pull request by ilovezfs**
Simplify Solver's task by requesting version 2.2.4.1 of the persistent
package instead of just providing the persistent < 2.5 constraint.

With only the persistent < 2.5 constraint, and with --flags=s3\ webapp
and --max-backjumps=10000, CI timed out after two hours with Solver
still trying to find a solution.

This is a follow-up to 18e458db, since there's been a regression in the
situation between 6.20160619 and 6.20160808, probably simply because
Hackage is a moving target.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@joeyh here we go again! :)

**Comment by ilovezfs** [comment]
Cf. https://github.com/Homebrew/homebrew-core/pull/3724.

**Comment by joeyh** [comment]
Please submit changes to http://git-annex.branchable.com/todo/ instead of using github pull requests, which are not part of my workflow. Just open a todo item there and link to a git repository containing your changes. Did you know, git is a distributed system? The git repository doesn't even need to be on github! Please send any complaints to Github; they don't allow turning off pull requests or redirecting them elsewhere.  -- A robot acting on behalf of Joey Hess

**Comment by ilovezfs** [comment]
Cf. http://git-annex.branchable.com/bugs/git-annex.cabal__58___persistent___61____61__2.2.4.1/?updated

**Comment by joeyh** [comment]
You have presented cabal with some dependency situation that causes its
solver to blow up. But AFAICS this is only the case in your own particular
environment; it's not the case in my envionment, or Debian's
environment, etc.

If homebrew needs particular dependency versions, you could specify them
locally in a local cabal.config file. Or you could use stack which
should always find a consistent set of dependencies.

I don't think it makes sense for git-annex to pin down versions like
this just because one build environment is having trouble. So I don't
plan to apply this patch.

-- 
see shy jo

**Comment by ilovezfs** [comment]
@joeyh did you actually try it with ghc 8 + s3 + webapp? That's not exactly exotic.

**Comment by joeyh** [comment]
ilovezfs wrote:
> @joeyh did you actually try it with ghc 8 + s3 + webapp? That's not exactly
> exotic.

I have not tried it with ghc 8. I don't think it was made clear that ghc 8
was part of the picture for this.

There is some stuff in cabal.config that was put there earlier to
support ghc 8.

-- 
see shy jo

**Comment by ilovezfs** [comment]
> I don't think it was made clear that ghc 8 was part of the picture for this.

Yeah, I assumed you'd remember my prior remarks about GHC 8 and Homebrew, namely that it's the only thing we currently support (we only basically support the current version of all things). Sorry for not mentioning that again.

**Comment by joeyh** [comment]
Just to show how complicated this can be, after merging this, the
windows autobuilder broke. Seems the bounds change caused it to need
to change the version of rersistent, and persistent-2.2.1 fails to
build on windows (while 2.2 works ok). At this point I have no earthly
idea how to fix the windows autobuilder without reverting this change.

Over-tight version bounds in the cabal file are horrible.

-- 
see shy jo

**Comment by ilovezfs** [comment]
@joeyh Ug, that's no good.

The right answer here is to get

https://github.com/prowdsponsor/esqueleto/pull/144
https://github.com/aristidb/aws/issues/206

resolved so this problem actually goes away.

**Pull request closed without merging**
