### PR TITLE
Fix and improve standalone build

### PR DESCRIPTION
**Pull request by yarikoptic**
Standalone was not installable on squeeze because of the git version.  Since per se externals git version doesn't matter beyond original clone (if I got it correctly) and all other tools are also shipped alone, in the first commit I just pruned all of those depends.  
In the 2nd commit I have avoided patching of debian/rules altogether to get proper version for snapshots and just make it more reliable.  The only problem with current '%'-powered setup is that upon finishing necessary action it still runs the main '%' rule:

```
$> debian/rules build-standalone-dsc SNAPSHOT_BUILD=1
...
make[1]: Leaving directory '/home/yoh/proj/git-annex'
dh build-standalone-dsc
dh: Unknown sequence build-standalone-dsc (choose from: binary binary-arch binary-indep build build-arch build-indep clean install install-arch install-indep)
debian/rules:15: recipe for target 'build-standalone-dsc' failed
make: *** [build-standalone-dsc] Error 25
```

any idea @joeyh either it is preventable?

### CODE REVIEW

**Comment by joeyh** [comment]
Please submit changes to http://git-annex.branchable.com/todo/ instead of using github pull requests, which are not part of my workflow. -- A robot acting on behalf of Joey Hess

**Comment by joeyh** [comment]
Yaroslav Halchenko wrote:
> In the 2nd commit I have avoided patching of debian/rules altogether to get
> proper version for snapshots and just make it more reliable. The only problem
> with current '%'-powered setup is that upon finishing necessary action it still
> runs the main '%' rule:
> 
> $> debian/rules build-standalone-dsc SNAPSHOT_BUILD=1
> ...
> make[1]: Leaving directory '/home/yoh/proj/git-annex'
> dh build-standalone-dsc
> dh: Unknown sequence build-standalone-dsc (choose from: binary binary-arch binary-indep build build-arch build-indep clean install install-arch install-indep)
> debian/rules:15: recipe for target 'build-standalone-dsc' failed
> make: *** [build-standalone-dsc] Error 25
> 
> any idea @joeyh either it is preventable?

Why not just put a target in Makefile rather than using debian/rules at
all?

-- 
see shy jo

**Comment by yarikoptic** [comment]
I could do that (define those dpkg-buildpackage ones) in Makefile indeed.  I just thought that it is better to keep debian-related stuff under debian/ .  I will send a PR for that shortly

**Comment by yarikoptic** [comment]
@joeyh  could you please make RELEASE_BUILD handling in Annex a bit more "sophisticated" that "=0" would assume a non-release build? ;)  that would avoid me needing yet another SNAPSHOT_BUILD variable

**Comment by joeyh** [comment]
Yaroslav Halchenko wrote:
> @joeyh could you please make RELEASE_BUILD handling in Annex a bit more
> "sophisticated" that "=0" would assume a non-release build? ;) that would avoid
> me needing yet another SNAPSHOT_BUILD variable

sure; done

-- 
see shy jo

**Pull request closed without merging**
