### PR TITLE
Enh standalone build

### PR DESCRIPTION
**Pull request by yarikoptic**
Something like that?  Probably

- should build just a source package (to be then deferred to whatever builder is supposed to build binaries)
- ATM refers to  neurodebian   as the suite and adds neurodebian specific ```~nd``` version suffix.  What would you advise to do instead?

### CODE REVIEW

**Comment by joeyh** [comment]
Suggest using git-annex version --raw to get the version, which will include the git ref in the way git-annex uses it when a non-release build is made.

Using the neurodebian stuff seems expedient, maybe not ideal long-term.

**Comment by yarikoptic** [comment]
1. for "git-annex version --raw" I would need first to build it... or there is a quick way?

2. sure -- I can remove neurodebian mentioning, but what suite should it target for upload? UNRELEASED?

**Comment by joeyh** [comment]
Yaroslav Halchenko wrote:
>  1. for "git-annex version --raw" I would need first to build it... or there is
>     a quick way?

I hacked around that.

>  2. sure -- I can remove neurodebian mentioning, but what suite should it
>     target for upload? UNRELEASED?

No idea. :)

-- 
see shy jo

**Comment by joeyh** [comment]
Please submit changes to http://git-annex.branchable.com/todo/ instead of using github pull requests, which are not part of my workflow. -- A robot acting on behalf of Joey Hess

**Pull request closed without merging**
