### PR TITLE
proxy support?

### PR DESCRIPTION
**Pull request by kiwiroy**
Almost completely no idea what I'm doing here, 30 mins with [YAHT](https://en.wikibooks.org/wiki/Haskell/YAHT) isn't much, but changes are extracted from [cookbook](http://www.stackage.org/package/http-client) in a vain hope they compile and can be integrated...

My aim is to fix primarily [S3](http://git-annex.branchable.com/forum/Pushing_git_repo_to_AWS_S3_from_behind_proxy/), but possibly also [box.com](https://git-annex.branchable.com/bugs/Proxy_support/).

Either way, I'd appreciate a method to have git annex traverse a firewall through a proxy server.

### CODE REVIEW

**Comment by joeyh** [comment]
Roy Storey wrote:
> Almost completely no idea what I'm doing here, 30 mins with YAHT isn't much,
> but changes are extracted from cookbook in a vain hope they compile and can be
> integrated...
> 
> My aim is to fix primarily S3, but possibly also box.com.

This looks like the right approach, so I've added it as a link to the
existing bug report about this,
http://git-annex.branchable.com/bugs/Proxy_support

git-annex supports being built with older versions of http-client that
don't have this proxy support, but that's no big problem, I can adapt
the patches to use idefs.

Want to expand the patch from S3 to also cover the WebDAV support,
and the http-conduit use in Utility.Url? I think those are the three
places where http proxy should be used.

-- 
see shy jo

**Comment by kiwiroy** [comment]
@joeyh thanks for the response. Sorry expanding the patch to cover WebDAV and Utility.Url is way beyond my Haskell foo.

**Comment by joeyh** [comment]
Please submit changes to http://git-annex.branchable.com/todo/ instead of using github pull requests, which are not part of my workflow. -- A robot acting on behalf of Joey Hess

**Comment by joeyh** [comment]
Roy Storey wrote:
> @joeyh thanks for the response. Sorry expanding the patch to cover WebDAV and
> Utility.Url is way beyond my Haskell foo.

Well, good news, it turns out simply rebuilding git-annex with a newer
version of the http-proxy haskell library should automatically enable
support for the proxy env vars; no code change needed.

-- 
see shy jo

**Pull request closed without merging**
